[package]
name = "midi-graph"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
midly = "0.5.3"
wav = "1.0.0"
cpal = { version = "0.15.2", features = ["wasm-bindgen"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.84"
