[package]
name = "midi-graph-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
midi-graph = { path = "../" }
wasm-bindgen = "0.2.84"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
opt-level = "s"
